### ISSUE TITLE
Incompatiblity with Intellij Idea 2021.1.1

### ISSUE THREAD

**Issue by fbouliane** [nokia/PyVenvManage#15]
Happenned after upgrading to 2021.1.1 from 2021.1.0
Build info
```
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.max.recent.projects=30, ide.mac.file.chooser.native=false
Non-Bundled Plugins: com.github.nokia.pyvenv (1.3.1), YAML/Ansible support (0.11.2), com.jetbrains.plugins.ini4idea (211.6693.44), org.jetbrains.plugins.rest (211.6693.44), com.intellij.lang.puppet (211.6693.44), org.plugin.dot.id (1.2), org.toml.lang (0.2.146.3826-211), ru.meanmail.plugin.requirements (2021.4-211), com.dmarcotte.handlebars (211.6693.44), org.jetbrains.plugins.vue (211.7142.13), com.jetbrains.php (211.7142.45), com.jetbrains.php.behat (211.6693.65), com.jetbrains.php.codeception (211.6693.65), com.jetbrains.php.dql (211.6693.65), com.jetbrains.twig (211.6693.44), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.208), org.jetbrains.plugins.ruby (211.7142.36)
Kotlin: 211-1.4.32-release-IJ7142.27
Current Desktop: ubuntu:GNOME
```
With PyVenv Manage 1.3.1

```
com.intellij.diagnostic.PluginException: com/jetbrains/python/sdk/PythonSdkType [Plugin: com.github.nokia.pyvenv]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:250)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/python/sdk/PythonSdkType
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:233)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.python.sdk.PythonSdkType PluginClassLoader(plugin=PluginDescriptor(name=PyVenv Manage, id=com.github.nokia.pyvenv, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2021.1/PyVenv Manage, version=1.3.1, package=null), packagePrefix=null, instanceId=1, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 26 more
```

**Comment by andrask** [comment]
@fbouliane I started the version you mention but didn't see the error. However, I cannot see the python plugin being listed in your plugin list. It is listed as an optional dependency to allow the PyVenvManage to be installed freely in any Jetbrains IDE.

Could you please ensure the python plugin to be installed?

**Comment by fbouliane** [comment]
Yes,
The plugin was automatically removed during an upgrade from 2021.1.0 ... I'm not sure why.
Reinstalling it fixed the issue.
Thanks for the help.

Nice plugin btw ... Really simplifies working with tox and venvs 👍

**Comment by andrask** [comment]
@fbouliane Thank you. I use it all the time too. You can leave a rating or review on the plugin page, too https://plugins.jetbrains.com/plugin/10085-pyvenv-manage I'm happy to see feedback.
